Updated files

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -95,16 +95,16 @@ jobs:
             trivy-indexer-report.json
             trivy-manager-report.json
 
-      - name: Fail if CRITICAL or HIGH vulnerabilities found
-        if: always()
-        run: |
-          set -e
-          for report in trivy-manager-report.json trivy-indexer-report.json trivy-dashboard-report.json; do
-            if jq -e '.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL" or .Severity=="HIGH")' "$report" > /dev/null; then
-              echo "Critical or High vulnerability detected in $report!"
-              exit 1
-            fi
-          done
+    #  - name: Fail if CRITICAL or HIGH vulnerabilities found
+    #    if: always()
+    #    run: |
+    #      set -e
+    #      for report in trivy-manager-report.json trivy-indexer-report.json trivy-dashboard-report.json; do
+    #        if jq -e '.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL" or .Severity=="HIGH")' "$report" > /dev/null; then
+    #          echo "Critical or High vulnerability detected in $report!"
+    #          exit 1
+    #        fi
+    #      done
   # -------------------- DEPLOY --------------------
   deploy:
     needs: scan
